site_name: XIA online GUI
site_url: https://kinstaky.github.io/xia-daq-gui-online
site_author: pwl

repo_url: https://github.com/kinstaky/xia-daq-gui-online
repo_name: kinstaky/xia-daq-gui-online

theme:
  name: material
  palette:
    primary: deep purple
  language: zh
  features:
    - content.code.copy
    - navigation.expand
  icon:
    repo: fontawesome/brands/github

extra:
  version:
    - provider: mike
    - default: latest

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      pygments_lang_class: true
      linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true
  - github-callouts

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - 简介: index.md
  - 用户指南:
    - 上手指南: getting_started.md
    - 模板详解: template_walk_through.md
    - 示例详解: example_details.md
  - 开发指南:
    - 内存模型: memory_model.md
    - 获取代码详解: daq_walk_through.md
    - 在线接收详解: online_receiver.md
  - 附录:
     - 在 Ubuntu 中编译 PLX-SDK: compile_plxsdk_ubuntu.md